Add 'HasNext', 'Next', and 'All' methods to PageIterator
microsoftgraph/msgraph-sdk-go-core pull request #229
Opened 2023-09-17 17:45 UTC by eric-millin

## Overview

Adds `HasNext`, `Next`, and `All` methods to `PageIterator`. These methods allow iteration without callbacks. 

This refactor also changes the behavior of `Iterate`. Previously, the iterator would never advance to the next page if the callback always returned `false` to pause iteration. It now does.

## Testing

Unit tests included.

2023-09-19 23:03 UTC, rkodev requested changes
@eric-millin Thanks for the contribution.  Left a comment but overall this look good

2023-09-19 23:03 UTC, rkodev commented on page_iterator.go
> +		pI.GetOdataNextLink() != nil && *pI.GetOdataNextLink() != ""
defensive programing , we can check if the next link is a white space using `strings.TrimSpace(s)`

2023-09-25 18:39 UTC, rkodev approved these changes

2023-09-26 12:13 UTC, baywet approved these changes
Thanks for the contribution!

2023-09-26 12:14 UTC, baywet commented
@eric-millin would you mind also adding a entry to the changelog please? 
(bump the patch, use the date of tomorrow, and add your changes under an added section)
Thanks!

2023-10-06 13:34 UTC, baywet commented
@eric-millin no, sorry I got mixed up with partial diffs in GitHub and forgot it was already there.
@rkodev for merge and publish

2023-10-20 18:22 UTC, eric-millin commented
@baywet @rkodev There's an edge case bug during iteration. If page A has an `odata.next` field, but the following page has empty `values`, then `Next(ctx)` returns `nil`, which isn't what we want, I think.

I'm going to close this PR, fix it, and then can re-open or create a new PR.

2023-10-20 18:22 UTC, closed without merging