fix page iterator bug
microsoftgraph/msgraph-sdk-go-core pull request #42
Opened 2022-02-04 09:28 UTC by jobala

## Overview

Fixes #41 

## Demo
N/A

## Notes
N/A

## Testing
* Run `go test`

2022-02-04 13:30 UTC, baywet requested changes
thanks for taking care of this.
can we tackle #40 as part of this PR as well please? (updating the regex)
also, missing changelog entry

2022-02-04 18:22 UTC, ddyett approved these changes
Tested and looks good.

2022-02-07 13:22 UTC, baywet requested changes

2022-02-07 13:22 UTC, baywet commented on graph_odata_query_handler.go
> +	replacementRegexp := "(?i)([^$|$])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
```suggestion
	replacementRegexp := "(?i)([^$|4])(count|deltatoken|expand|filter|format|orderby|search|select|skip|skiptoken|top)="
```

2022-02-07 13:25 UTC, baywet approved these changes

2022-02-07 13:27 UTC, merged